### ISSUE TITLE
Files size increase from 250 kB to 2.7 MB after removing fonts

### ISSUE THREAD

**Issue by paulmenzel** [tdegeus/pdfnofonts#11]
$ ls -l test.pdf
    -rw-rw-r--   1 pmenzel pmenzel     253881 13. Jul 07:34  test.pdf

    $ pdffonts test.pdf
    name                                 type              encoding         emb sub uni object ID
    ------------------------------------ ----------------- ---------------- --- --- --- ---------
    BCDEEE+Roboto-Regular                TrueType          WinAnsi          yes yes no       7  0
    BCDFEE+Roboto-Regular                CID TrueType      Identity-H       yes yes yes     10  0
    BCDGEE+Roboto-Black                  TrueType          WinAnsi          yes yes no      15  0
    BCDHEE+Calibri-Bold                  TrueType          WinAnsi          yes yes no      17  0
    BCDIEE+Calibri                       TrueType          WinAnsi          yes yes no      19  0
    BCDJEE+Calibri                       CID TrueType      Identity-H       yes yes yes     23  0
    $ pdfnofonts --version
    1.1.0
    $ pdfnofonts test.pdf
    $ ls -l test.pdf
    -rw-rw-r--  1 pmenzel pmenzel  2812514 13. Jul 07:35  test.pdf
    $ pdffonts test.pdf
    name                                 type              encoding         emb sub uni object ID
    ------------------------------------ ----------------- ---------------- --- --- --- ---------

So the fonts are remove but the size increase from 248 KB to 2.7 MB.

**Comment by tdegeus** [comment]
Thanks for the report. I think that this is an upstream issue that should be reported to ghostcript. In the end, this code does nothing else then to run 

https://github.com/tdegeus/pdfnofonts/blob/6eb4b7e44316c1172ffedc4f4093d16b02c64785/pdfnofonts/__init__.py#L54C12-L54C67
